### PR TITLE
Add user model

### PR DESCRIPTION
**Pull request by dan-f**
@jimabramson @tlindaliu please review

### CODE REVIEW

**Comment by jimabramson** [comment]
@dan-f can you get travis to use test settings instead of local, and get mongo working on the travis side?

**Comment by dan-f** [comment]
got it @jimabramson

**Comment by dan-f** [comment]
@jimabramson fixed tests. Punting mongo until we actually make use of it in a test. (Thanks for the link on [how to do that](https://github.com/edx/cs_comments_service/blame/master/.travis.yml#L13)).

**Comment by jimabramson** [comment]
:+1:

**Comment by tlindaliu** [comment]
:+1:

**Pull request merged**
